### ISSUE TITLE
Unable to fetch the project

### ISSUE THREAD

**Issue by sachs4** [seL4/verification-manifest#1]
As said in the build description I do:
$ repo init -u https://github.com/seL4/verification-manifest.git
$ repo sync

It seems like the project HOL is downloaded successfully, but when repo is trying to fetch the project isabelle I get the following error message:
"fatal: Couldn't find remote ref refs/tags/Isabelle2016
Unexpected end of command stream"

**Comment by lsf37** [comment]
That's mildly embarrassing. It appears the revision has been synced, but not the tag name. This should be fixed now. Can you please try again?

**Comment by sachs4** [comment]
Thank you, isabelle now fetches fine, but when downloading the seL4 repo another error shows up: 
"error.GitError: seL4 update-ref: fatal: 541289a32603cee8242b5360b05e8f0c52795433^0: not a valid SHA1".
I just figured out how to download the 3.0.x.xml version directly, which works fine for me, and is absolutely enough for my purposes.

**Comment by lsf37** [comment]
That sounds even more worrying, it looks like the deployment tool chain is having hiccups. We will investigate. It's possible that the proof will work with 3.0.x, but not that likely (only if nothing verification-relevant changed in the 3.0.x releases).

**Comment by lsf37** [comment]
With the latest version this looks resolved now as far as I can see. Please try again and if it still doesn't work for you, please do reopen the issue.

**Comment by zagol** [comment]
Hi, I followed the instructions. When I'm running repo sync, I hit the following error: 
"error: Cannot fetch l4v (GitError: l4v update-ref: fatal: 6991fab7e8997f2a0c2691e15cb852b1e97d4284^0: not a valid SHA1)"

Should I download and use 3.0.x.xml version directly as sachs4 did?

**Comment by lsf37** [comment]
Yes, this would probably work. Apart from that, I thought we had fixed that issue with our automated deployment chain (what you're seeing shouldn't be possible), but obviously not. We're looking into it.

**Comment by zagol** [comment]
Thanks.

**Comment by YakoubN** [comment]
Something is going wrong with the seL4 repo. It was working yesterday. I did a new setup for my machine and I have this error today:
error.GitError: seL4 update-ref: fatal: 7caa3d1919e488c1001a4338a54bcb49636d8dff^0: not a valid SHA1

**Comment by ajaysusarla** [comment]
@YakoubN a new release of seL4 was made late last evening and I guess revision and the tag name are out of sync(again). There seems to be a lag with the sync. We are looking into it. Sorry for the hassle and thanks for bringing it to our attention.

**Comment by YakoubN** [comment]
OK. Thank you for help.

**Comment by ajaysusarla** [comment]
@YakoubN We've fixed it now. Sorry again for the hassle. Also @agomezl, thanks much for the help!

**Comment by myuluo** [comment]
@ajaysusarla Can I download verifacition now ?

**Comment by ajaysusarla** [comment]
Hello @myuluo sorry for the delayed response, yes you can download and use seL4 verification now.

**Comment by ajaysusarla** [comment]
Closing the issue, since this has been fixed.

**Comment by Apromixately** [comment]
@ajaysusarla would you mind explaining what the issue was? I am seeing a similar problem on a different project. :)

**Comment by lsf37** [comment]
In this particular case it usually was a problem in our release scripts, where the manifest was pushed, but one of the repos not yet, so either a tag or even the actual change set wasn't there yet.
