### ISSUE TITLE
error.GitError: polyml update-ref: fatal: cea4c79cc7ef2445a0600f1be41acb3a97c16e01^0: not a valid SHA1

### ISSUE THREAD

**Issue by SeoyeonHwang** [seL4/verification-manifest#2]
Hello, I've been trying to install this repo (following all the steps in https://docs.sel4.systems/projects/buildsystem/host-dependencies.html), but when I try "repo sync" it causes an error like below:

remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 154540 (delta 2), reused 4 (delta 2), pack-reused 154532
Receiving objects: 100% (154540/154540), 94.73 MiB | 11.05 MiB/s, done.
Resolving deltas: 100% (116232/116232), done.
Fetching projects:  16% (1/6) HOLremote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 31384 (delta 37), reused 37 (delta 30), pack-reused 31322
Receiving objects: 100% (31384/31384), 86.78 MiB | 11.08 MiB/s, done.
Resolving deltas: 100% (25303/25303), done.
error: Cannot fetch polyml (GitError: polyml update-ref: fatal: cea4c79cc7ef2445a0600f1be41acb3a97c16e01^0: not a valid SHA1

**Comment by lsf37** [comment]
Thanks for reporting that. It looks like there is something going slightly wrong in `repo` somehwere. The sha in the manifest is  `cea4c79cc7ef2445a0600f1be41acb3a97c16e01`, which is correct, but it's reporting `cea4c79cc7ef2445a0600f1be41acb3a97c16e01^0` in the error message.

In the directory in which you did `repo init -u ..`, could you have a look at the file `.repo/manifests/default.xml`?

Line 11 of that file should read:
```xml
  <project dest-branch="successful-decompile" name="polyml" path="HOL4/polyml" remote="projects" revision="cea4c79cc7ef2445a0600f1be41acb3a97c16e01" upstream="successful-decompile"/>
```
(no `^0` at the end of the revision).

Is that the case?

**Comment by SeoyeonHwang** [comment]
Thanks for the comments, but the file `default.xml` does have the same line as below (with no ^0 at the end). 

```
<manifest>
  <remote fetch="../sel4proj" name="projects"/>
  <remote fetch="." name="verification"/>

  <default remote="verification" revision="master"/>

  <project dest-branch="successful-decompile" name="HOL" path="HOL4" remote="projects" revision="6c2b347359d14514e88c56ae31d4cf5bff5a5e58" upstream="successful-decompile"/>
  <project dest-branch="master" name="graph-refine" revision="c3a38db3b3860228fcdd3aa5016163e72baeb158" upstream="master"/>
  <project name="isabelle" revision="refs/tags/Isabelle2020"/>
  <project dest-branch="master" name="l4v" revision="dbc735c81d72ce3dfac67a022cf0ff6ee18e36e7" upstream="master"/>
  <project dest-branch="successful-decompile" name="polyml" path="HOL4/polyml" remote="projects" revision="cea4c79cc7ef2445a0600f1be41acb3a97c16e01" upstream="successful-decompile"/>
  <project name="seL4" revision="b86bce2d4b11f9c4c5cd66c40eb47900bf51eaae"/>
  </manifest>
```

**Comment by lsf37** [comment]
Thanks for confirming, I now managed to reproduce it locally as well. It looks like that revision was indeed not on github yet (which it should have been, will need to investigate how this happened).

I've updated the repo manually now. Could you try `repo sync` again?

**Comment by SeoyeonHwang** [comment]
Now it worked well! Thanks so much for your rapid help! :)👍
