### ISSUE TITLE
default manifest points to old `sel4proj` repositories

### ISSUE THREAD

**Issue by mbrcknl** [seL4/verification-manifest#6]
(Mostly a note to self, since I don't have time to fix this right now.)

The `HOL4` and `polyml` entries in the default manifest (and probably also in others) point to repositories in the `sel4proj` organisation, but those repositories redirect back to the `seL4` organisation. This works, but we could update the manifests to point to the canonical locations to avoid confusion.

**Comment by lsf37** [comment]
Well spotted. There must be some special treatment somewhere in the scripts that produce `default.xml`. Most likely in `l4v-regression-bamboo/deploy/staging-manifest`

**Comment by lsf37** [comment]
It looks like it's preserving the remotes from the existing `default.xml`, so the only thing we need to do is remove it there. I'll try that and we'll see with the next update if it re-appears.

**Comment by lsf37** [comment]
Done in 957b2d7 - let's see how it goes..

**Comment by lsf37** [comment]
This seems to have worked as intended, e.g. 0cf3343bcb2324b79ea0b53c48ccb99e3f9611db was done by CI and does not contain the `projects` remote any more.

**Comment by mbrcknl** [comment]
Nice, thanks for taking care of that!
